# Site settings
title: Seaplain's Blog
email: seaplain1@gmail.com
description: I talk about Android development and other things
baseurl: "" 
url: "http://seaplain.com"
favicon: "/assets/site/favicon.ico"
theme_color: "#009688"
github_username: cplain
disqus_shortname: seaplain
excerpt_separator: <!--end_excerpt-->

# Build settings
markdown: kramdown
