# Site settings
title: Seaplain's Brain Dump
email: seaplain1@gmail.com
description: I talk about Android development and things I find in the tech world.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://seaplain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  cplain

# Build settings
markdown: kramdown
